apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-tomcat-application
  namespace: argocd
  annotations:
spec:
  project: default
  source:
    repoURL: https://github.com/brundabanm/myargo.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    syncOptions:
    - PruneLast=true 
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-springboot-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brundabanm/myargo.git
    targetRevision: HEAD
    path: qa
  destination:
    server: https://kubernetes.default.svc
    namespace: app-qa
  syncPolicy:
    syncOptions:
    - PruneLast=true 
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
